# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency_app.Category')),
            ],
        ),
    ]
